apiVersion: apps/v1
kind: Deployment
metadata:
  name: misinformation-mitigation-api
  labels:
    app: misinformation-mitigation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misinformation-mitigation-api
  template:
    metadata:
      labels:
        app: misinformation-mitigation-api
    spec:
      serviceAccountName: misinformation-mitigation-api
      containers:
      - name: misinformation-mitigation-api
        image: gcr.io/misinformation-mitigation/misinformation-mitigation-api:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://misinformation_mitigation_user:$(DB_PASSWORD)@/misinformation_mitigation_db?host=/cloudsql/misinformation-mitigation:northamerica-northeast1:misinformation-mitigation-db"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: misinfo-db-secrets
              key: db-password
        volumeMounts:
          - name: cloudsql
            mountPath: /cloudsql
        # readinessProbe:
        #   httpGet:
        #     path: /v1/health
        #     port: 8001
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          - "--private-ip"
          - "--structured-logs"
          - "--unix-socket=/cloudsql"
          - "misinformation-mitigation:northamerica-northeast1:misinformation-mitigation-db"
        volumeMounts:
          - name: cloudsql
            mountPath: /cloudsql
        securityContext:
          runAsNonRoot: true
      volumes:
        - name: cloudsql
          emptyDir: {}
      restartPolicy: Always
        
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: misinformation-mitigation-api
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: misinfo-mitigation-gke-sa@misinformation-mitigation.iam.gserviceaccount.com
---
apiVersion: v1
kind: Service
metadata:
  name: misinformation-mitigation-api-service
spec:
  type: LoadBalancer
  selector:
    app: misinformation-mitigation-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: misinformation-mitigation-api-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "misinformation-mitigation-api-ip"
    networking.gke.io/managed-certificates: "misinformation-mitigation-api-cert"
spec:
  rules:
  - host: api.veri-fact.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: misinformation-mitigation-api-service
            port: 
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: misinformation-mitigation-api-cert
spec:
  domains:
    - api.veri-fact.ai
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: misinformation-mitigation
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: misinfo-db-secrets
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: misinfo-db-secrets
  data:
  - secretKey: db-password
    remoteRef:
      key: misinfo-db-password